### ISSUE TITLE
[QUESTION] Can't open GUI

### ISSUE THREAD

**Issue by hron84** [tcooc/AdditionalPipesBC#131]
With AdditionalPipes 4.6.1 I am not able to open the GUI of the teleport pipes. I tried with empty hand right click, sneak+right click, with various wrenches (left, right, shift+left, shift+right clicks) and no luck. Could you please explain me how do you open Teleport Pipe GUIs? 

BC 7.1.5
AP 4.6.1

**Comment by multiplemonomials** [comment]
The problem is that in BC 7.1, they changed the signature of the Pipe.blockActivated() function, so my overrides in Additional Pipes don't get triggered.  Additional Pipes 4.6.1 is for BC 7.0.x only.  I haven't released a version which does work yet because I'm in the middle of the whole Logistics Pipes project.  I'm assuming you need such a version for your testing, so here are the [mod](https://dl.dropboxusercontent.com/u/27566023/Software%20Host/additionalpipes-4.7.0-beta2.jar), [dev](https://dl.dropboxusercontent.com/u/27566023/Software%20Host/additionalpipes-4.7.0-beta2-dev.jar), and [source](https://dl.dropboxusercontent.com/u/27566023/Software%20Host/AdditionalPipes-4.7.0-beta2-src.zip) jars.  These include the fixed SpecialPipeConnection code that I mentioned in the main LP issue.

**Comment by hron84** [comment]
@multiplemonomials I have to use BC 7.1 because LP moved to there, and I building a tech-based modpack for a small, closed community that wants to use  LP. Thanks for the possibility to try out the beta2 jar. Do you agree if we can use this beta to our private closed server too (assuming we accept this is a beta version)? Maybe we can produce a good feedback about the changes included in this version as I usually report issues directly to mod developers if I find any.

**Comment by multiplemonomials** [comment]
Sure, it's fine.  I'm still stuck on the logistics pipes compatibility; items don't get routed through the teleport pipes.

**Comment by hron84** [comment]
It's ok, we have OC.
